export  {Buttons1}  from './Buttons/Buttons'
export {default as News} from './News/News'
export {default as Containeree} from './Containeree/Containeree'
export {default as Buttons} from './Buttons/Buttons'
export {default as Only_person} from './Only_person/Only_person' 
export {default as Only_friends} from './Only_friends/Only_friends'
export {default as OnlyStorie} from './OnlyStorie/OnlyStorie'
export {default as Representure} from './Representure/Representure' 
export {default as Works} from './Works/Works'   
export {default as Isocial_zone} from './Isocial_zone/Isocial_zone'
export {default as Only_friens} from './Only_friens/Only_friens'
export {default as Post} from './Post/Post'
